#!/usr/bin/env bash

debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password password password'
debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password_again password password'

apt-get update
apt-get -y install python-software-properties
apt-add-repository -y ppa:git-core/ppa
apt-get update
apt-get -y --allow-unauthenticated install git
apt-get install -y build-essential openssl libssl-dev curl
apt-get install -y python-dev libxml2-dev libxslt1-dev
