#!/usr/bin/env bash
apt-get install -y mysql-server --fix-missing --fix-broken

if [ ! -f /var/log/databasesetup ];
then
    echo "CREATE DATABASE mhcm" | mysql -uroot -ppassword

    php /vagrant/artisan migrate
    php /vagrant/artisan db:seed

    touch /var/log/databasesetup
fi
