#!/usr/bin/env bash
apt-add-repository -y ppa:ondrej/php5-oldstable
apt-get update
apt-get install -y php5 php5-cli php5-fpm php5-mysql php5-mcrypt php5-xsl php5-curl

dd if=/dev/zero of=/swapfile bs=1024 count=512k
mkswap /swapfile
swapon /swapfile

cd /vagrant
curl -sS https://getcomposer.org/installer | php

php composer.phar install

echo "user = vagrant" >> /etc/php5/fpm/pool.d/www.conf
echo "group = vagrant" >> /etc/php5/fpm/pool.d/www.conf
