#!/usr/bin/env bash
apt-add-repository -y ppa:ondrej/php5-oldstable
apt-get update
apt-get install -y php5 php5-cli php5-fpm php5-mysql php5-mcrypt php5-xsl php5-curl

cd /vagrant
curl -sS https://getcomposer.org/installer | php

php composer.phar install
