#!/usr/bin/env bash

curl -L get.rvm.io | bash -s stable --auto-dotfiles

source "$HOME/.rvm/scripts/rvm"

echo 'gem: --no-ri --no-rdoc' >> ~/.gemrc

rvm requirements

rvm install 2.1.1
rvm --default use 2.1

gem update --system

gem install bundler
