#!/usr/bin/env bash
apt-get install -y nginx

cp /vagrant/.provisioning/files/conf.nginx /etc/nginx/nginx.conf
cp /vagrant/.provisioning/files/serverblocks.nginx /etc/nginx/sites-available/mhcm.dev

ln -s /etc/nginx/sites-available/mhcm.dev /etc/nginx/sites-enabled/mhcm.dev

mkdir -p /etc/nginx/ssl/
openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=SE/ST=Denial/L=Katrineholm/O=Dis/CN=mhcm.dev" -keyout /etc/nginx/ssl/snake-oil.key  -out /etc/nginx/ssl/snake-oil.crt

service nginx start
